version: "3.9"

services:
  postgres:
    container_name: psql
    image: postgres:latest
    ports:
      - 6432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    restart: always

volumes:
  db:
